[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra
# Last matching rule wins; rules are evaluated from bottom to top.
filterwarnings =
    error::DeprecationWarning
    error::ResourceWarning
    ignore:'crypt' is deprecated and slated for removal:DeprecationWarning
    ignore:datetime.datetime.utcnow\(\) is deprecated:DeprecationWarning
